### ISSUE TITLE
Fehler beim Aufruf

### ISSUE THREAD

**Issue by Maestro2k5** [RootService/tuning-primer#1]
./tuning-primer.sh: Zeile 4: Syntaxfehler beim unerwarteten Wort »newline«
./tuning-primer.sh: Zeile 4: `<!DOCTYPE html>'

Diesen Fehler erhalte ich.

**Comment by JoeUser78** [comment]
Du hast das Script falsch heruntergeladen.

**Comment by Maestro2k5** [comment]
Wieso das denn?

**Comment by JoeUser78** [comment]
Weil die Fehlermeldung eindeutig von einem HTML-Dokument hervorgerufen wurde, das Script aber keinerlei HTML enthält: https://raw.githubusercontent.com/RootService/tuning-primer/master/tuning-primer.sh
Somit kommt nur ein Fehler beim Download in Frage und das ist kein Bug.

**Comment by Maestro2k5** [comment]
Danke, Fehler gefunden es geht zwar tro trotzdem nicht aber der besagte
Fehler lag eindeutig bei mir.
Am 06.10.2015 01:56 schrieb "Joe User" notifications@github.com:

**Comment by JoeUser78** [comment]
Was genau funktioniert denn nicht? Gegebenenfalls bitte einen neuen Bugreport verfassen, danke.

**Comment by Maestro2k5** [comment]
Das wäre der Fehler. Hatte aber nicht weiter getestet. Vermutlich wieder
ein Fehler meinerseits.

Error: Needed command "umask" not found in PATH!

2015-10-06 12:36 GMT+02:00 Joe User notifications@github.com:

> Was genau funktioniert denn nicht? Gegebenenfalls bitte einen neuen
> Bugreport verfassen, danke.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RootService/tuning-primer/issues/1#issuecomment-145818072
> .

## 

hirtec@android-port.de | www.android-port.de

_Android-Port auf den sozialen Netzwerken:_
Facebook: https://www.facebook.com/androidport
Google +:  https://plus.google.com/114526891987440481984/posts
Twitter: https://twitter.com/android_port

**Comment by JoeUser78** [comment]
Machst Du dafür bitte einen neuen Bugreport auf, danke.
