### ISSUE TITLE
Error: Needed command "umask" not found in PATH!

### ISSUE THREAD

**Issue by Maestro2k5** [RootService/tuning-primer#2]
Hallo,

ich wollte das Script soeben ausführen und erhielt folgenden Fehler.

Error: Needed command "umask" not found in PATH!

OS: ‪Ubuntu 14.04.3 LTS‬

**Comment by JoeUser78** [comment]
Der Bug wird heute gefixt.

**Comment by JoeUser78** [comment]
Bug fixed https://github.com/RootService/tuning-primer/commit/cbb1323d8e7a05016e09b91e4e4e19d8d1d1824a
