### ISSUE TITLE
Error: Needed command "ulimit" not found in PATH!

### ISSUE THREAD

**Issue by Maestro2k5** [RootService/tuning-primer#3]
Neues Spiel, neues Glück ... neuer Fehler beim ausführen

Error: Needed command "ulimit" not found in PATH!

**Comment by JoeUser78** [comment]
Bug fixed https://github.com/RootService/tuning-primer/commit/b245129d3171ffbd9f554a19e3426903df90a80e

**Comment by optyfr** [comment]
on Linux ulimit is a shell builtin, so "which" command will always return "not found", and the script is not working anymore because of that...

**Comment by JoeUser78** [comment]
Please open a bugreport at your distributions bugtracker since your distribution violates POSIX
https://bugzilla.redhat.com/show_bug.cgi?id=698670

In other words, this script is correct, your distribution is broken.

**Comment by optyfr** [comment]
So Debian 8, Debian 9, Gentoo, Centos 6.9, ... are violating POSIX then... and so do you mean that now tuning-primer is only BSD and SunOS compatible? 
please consider testing return code for "type <command>"  if "which" fail

**Comment by JoeUser78** [comment]
Yes, distributions not providing the binaries are violating POSIX, see the redhat bug 698670 for more information.

Nonetheless i changed the script to use builtins instead of binaries.
Hope that helps with broken linux systems.
