### ISSUE TITLE
How to use this tool with a remote host?

### ISSUE THREAD

**Issue by fabioce** [RootService/tuning-primer#4]
Hello,
Is possible to use this brilliant tool with a remote host?
thanks

**Comment by JoeUser78** [comment]
Hi,
yes, just download to the remote host, chmod 0755 and run it.

**Comment by fabioce** [comment]
I can't because I'm using AWS RDS

**Comment by JoeUser78** [comment]
In that case you can't use this or any other command line tool, sorry.
