### ISSUE TITLE
Can not use script all of sudden

### ISSUE THREAD

**Issue by xrvel** [RootService/tuning-primer#7]
When i type this : 

./tuning-primer.sh

No output in my SSH console.
Strange thing is i can type anything to the SSH console.
How to fix this?

Thank you.

**Comment by DrTyrell** [comment]
chmod +x tuning-primer.sh

**Comment by xrvel** [comment]
I've just tried it, still didn't work. I think it is my server issue. So i will close this.

Thank you.

**Update** : ok so i just need to wait +- 1-2 minutes, until tuning primer echoes the output.
