### ISSUE TITLE
Key Buffer: Runtime error (func=(main), adr=10): Divide by zero

### ISSUE THREAD

**Issue by maximmasiutin** [RootService/tuning-primer#8]
Thank you for your wonderful program!

I'm getting the following errors each time I run it:

KEY BUFFER
Runtime error (func=(main), adr=10): Divide by zero
(standard_in) 1: syntax error
Current MyISAM index space = 9 K
Current key_buffer_size = 0 bytes
Key cache miss rate is 1 : 1
Key buffer free ratio =  %
tuning-primer.sh: line 795: [: -le: unary operator expected
tuning-primer.sh: line 799: [: -le: unary operator expected
tuning-primer.sh: line 803: [: -le: unary operator expected
Your key_buffer_size seems to be fine

I'm using Ubuntu 14.04 LTS, GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu), mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (x86_64) using readline 6.3.

Thank you again!

**Comment by JoeUser78** [comment]
Setting key_buffer_size = 0 is not supported by tuning-primer and also not recommended by MySQL
