### ISSUE TITLE
mysql-version number check throws "Illegal number" error (octal versus decimal)

### ISSUE THREAD

**Issue by Archetrix** [RootService/tuning-primer#9]
When executing this script i end up with this error:
./tuning-primer.sh: 1323: ./tuning-primer.sh: Illegal number: 050718

Tracing the source it's where the mysql version number is checked.
I've uncommented the check to make it work, but then other checks throughout the script fire the same error.
In my opinion this is due to numbers with leading zeros considered being octal instead of decimal. in octal you only have 0-7 making the 8 at the end of my version number "illegal"

**Comment by JoeUser78** [comment]
Thanks for your report, i fixed it.
